//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepuestosServicio.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public partial class DetalleServicio
    {
        public int codigo { get; set; }
        public int id_servicio { get; set; }
        public int id_venta { get; set; }
        public decimal valor { get; set; }
        public string duracion { get; set; }

        [JsonIgnore]
        public virtual Servicio Servicio { get; set; }
        [JsonIgnore]
        public virtual Venta_Servicio Venta_Servicio { get; set; }
    }
}
