//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepuestosServicio.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public partial class DetalleVenta
    {
        public int codigo { get; set; }
        public int id_venta { get; set; }
        public int id_repuesto { get; set; }
        public int cantidad { get; set; }
        public decimal valor_unitario { get; set; }

        [JsonIgnore]
        public virtual Repuesto Repuesto { get; set; }
        [JsonIgnore]
        public virtual Venta_Repuesto Venta_Repuesto { get; set; }
    }
}
