//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepuestosServicio.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public partial class Moto
    {
        public string linea { get; set; }
        public Nullable<int> modelo { get; set; }
        public Nullable<int> id_marca { get; set; }
        public Nullable<int> id_cilindraje { get; set; }
        public string placa { get; set; }
        public string id_cliente { get; set; }

        [JsonIgnore]
        public virtual Cilindraje Cilindraje { get; set; }
        [JsonIgnore]
        public virtual Cliente Cliente { get; set; }
        [JsonIgnore]
        public virtual Marca Marca { get; set; }
    }
}
