//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepuestosServicio.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Repuesto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Repuesto()
        {
            this.Venta_Repuesto = new HashSet<Venta_Repuesto>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string numero_referencia { get; set; }
        public string numero_serie { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
        public Nullable<int> id_tipo_repuesto { get; set; }
        public Nullable<int> id_marca { get; set; }
        public Nullable<int> id_proveedor { get; set; }

        [JsonIgnore]
        public virtual Marca Marca { get; set; }
        [JsonIgnore]
        public virtual Proveedor Proveedor { get; set; }
        [JsonIgnore]
        public virtual Tipo_Repuesto Tipo_Repuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Venta_Repuesto> Venta_Repuesto { get; set; }
    }
}
