//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepuestosServicio.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public partial class Usuario
    {
        public int id { get; set; }
        public string id_empleado { get; set; }
        public string user_name { get; set; }
        public string clave { get; set; }
        public string salt { get; set; }

        [JsonIgnore]
        public virtual Empleado Empleado { get; set; }
    }
}
